field: 1cc25933-d89f-446d-a114-b66154169e66 # Materiaal lijst
fieldLayouts:
  fa28d3c4-eaf6-4cea-95d7-52cecd512f0c:
    tabs:
      -
        elements:
          -
            fieldUid: d18c16ef-3965-4d12-9400-4db1d4c697e4 # benaming materiaal
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04f7926c-200d-4cd3-b99b-1e93a1fdd24d
            warning: null
            width: 100
          -
            fieldUid: f9172996-eb36-48fb-84f8-4f35c3728c65 # hoeveelheid materiaal
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55657350-7b67-492d-a79b-5a08218f66a1
            warning: null
            width: 100
        name: Content
        uid: 0da3d828-8bfb-4a83-838c-d72c908d3fac
fields:
  d18c16ef-3965-4d12-9400-4db1d4c697e4: # benaming materiaal
    columnSuffix: eqhbxkdi
    contentColumnType: string
    fieldGroup: null
    handle: materialName
    instructions: null
    name: 'benaming materiaal'
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: 0
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionLabel: null
      showSiteMenu: true
      source: 'group:38a829e3-b181-49ee-baa2-561b893a6e0a' # Spel materiaal
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  f9172996-eb36-48fb-84f8-4f35c3728c65: # hoeveelheid materiaal
    columnSuffix: ieiwxqsw
    contentColumnType: integer(10)
    fieldGroup: null
    handle: materialAmount
    instructions: null
    name: 'hoeveelheid materiaal'
    searchable: false
    settings:
      decimals: 0
      defaultValue: 1
      max: null
      min: 1
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: materialItem
name: 'Materiaal item'
sortOrder: 1
