field: f2b91cbe-dc96-4130-a71f-326e99ec6d1e # testMatrix
fieldLayouts:
  243c6863-3f99-470f-af26-8797a609f03d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8086b01c-8350-4557-8e6e-60255bcc0337 # matrix Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4947bef4-8b7a-4d75-b16e-2e3392cb43e0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d084937e-0169-46e2-9fc8-996e457cdb13 # Matrix Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32b4bad5-3b68-49ea-a4cc-4f14ab4d25a3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41f9e44d-124d-41ff-a2a7-222278614aa6
        userCondition: null
fields:
  8086b01c-8350-4557-8e6e-60255bcc0337: # matrix Name
    columnSuffix: lkiahfau
    contentColumnType: text
    fieldGroup: null
    handle: matrixName
    instructions: null
    name: 'matrix Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d084937e-0169-46e2-9fc8-996e457cdb13: # Matrix Amount
    columnSuffix: eijjqhlv
    contentColumnType: text
    fieldGroup: null
    handle: matrixAmount
    instructions: null
    name: 'Matrix Amount'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: testmatrixblock
name: testMatrixBlock
sortOrder: 1
