fieldLayouts:
  a8e7690b-7a0b-4c6d-b8cf-3c145bdfba85:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6497f25-1c2b-4f51-a39a-84813148c924
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: d9e41ff9-18be-4637-89c7-576055a5aa38
        userCondition: null
handle: addCraft
hasTitleField: false
name: 'Knutselopdracht toevoegen'
section: adde1b0a-fe7f-4b28-8628-ae62f6ad5a5d # Knutselopdracht toevoegen
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
