fieldLayouts:
  5f099157-7e3c-4392-b5b7-c009e4b3e9cf:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bf06ce75-4112-42e7-81a4-2834250a9a3f
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 4ed7e279-e519-4535-8709-7721dd89a6f4
        userCondition: null
handle: default
hasTitleField: true
name: Standaard
section: 6f7fb0b4-c460-4f71-a9d6-80d4dfa91ef5 # Eén tegen allen opdrachten
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
