fieldLayouts:
  7aaa82ff-db83-467f-a378-35baf6c0941a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3c76893a-4bcb-4190-aece-02662fb1c210
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05c3f2cb-70ce-45fd-adde-74f4be96cf0f # redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5565593c-5189-4fa9-820b-e4a41d0095b3
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 017e4141-fa13-4d94-9a33-16477087f88e
        userCondition: null
handle: default
hasTitleField: true
name: Standaard
section: b9c67985-d40e-4cbd-996d-9b6f511a9f48 # Blogberichten
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
