fieldLayouts:
  a27e2daf-fd02-4201-aff0-d9c1ce668ed7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91fbfff0-6e84-4130-84bc-07e83023c2f0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89aeda29-7de1-4a24-b237-7ca544556d1a # Speluitleg
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e32503e-10d5-4bca-9b42-f2a1bb650f35
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 742bc565-d36b-4342-a2b3-9bc33225a57e
        userCondition: null
handle: default
hasTitleField: true
name: Standaard
section: 926861b1-5ccd-4b3d-985b-614aa962bc5d # Knutselopdrachten
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
