fieldLayouts:
  3b54177a-9fc7-4e10-8e60-07790c4ccce3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e31781f0-f7e9-48e7-9d12-6fc247534263
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d1b6141-70c2-4c2a-841b-a036eeb10aae # Link naar pagina
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 970e3108-4155-46ed-957e-e7fa0fd79df3
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 8ff10b1e-87f4-42e6-9fe3-f1a6b4c1d4fc
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: 9f4915ff-f144-41f9-b90e-4d517b0950bd # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
