fieldLayouts:
  26b6c1fd-b75e-4424-a4c4-6857e36e3488:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b566f51a-b593-46f3-90a9-e7f5c639e64d
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 995700fe-ad71-484a-80cf-839e92401e86
        userCondition: null
handle: myCrafts
hasTitleField: false
name: 'Mijn knutselopdrachten'
section: 8d3c63d4-dcaf-494b-b873-229679852123 # Mijn knutselopdrachten
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
