fieldLayouts:
  e293aff0-ec49-4e72-940b-c71f648770ad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 745b8605-e38d-4270-a07d-c156d467eedf
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: a24cd02f-d497-4290-a29b-286e45a79d7f
        userCondition: null
handle: myProfile
hasTitleField: true
name: 'Mijn Profiel'
section: 11b6b233-12c3-4b4f-8b21-7db92eb95807 # Mijn Profiel
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
