fieldLayouts:
  c41e529c-0c68-4ac2-aff4-269c16ebff8e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ab8ca93c-152f-460c-80e2-e1abda76ad27
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 49a80bee-bf01-44cd-9f68-ab21d3196d77
        userCondition: null
handle: overviewCrafts
hasTitleField: false
name: 'Overzicht knutselopdrachten'
section: a621ad91-c112-4a5d-aed1-9ebfb7b1fab6 # Overzicht knutselopdrachten
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
