fieldLayouts:
  651382ce-8a1c-4771-9ee3-e2be5fe0f9ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b6376a16-2881-4b63-8d93-99f5226a2403
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: f45f20bf-a75b-4464-9039-8a2d3be76f48
        userCondition: null
handle: passwordReset
hasTitleField: true
name: 'Wachtwoord Reset'
section: b92690fb-549e-494d-8c1b-1481340be882 # Wachtwoord Reset
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
