fieldLayouts:
  ca7f9449-d28f-4edb-8f5c-7e9ce6e7967c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8ab22afe-25e4-4e79-8bde-893f052e4166
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05c3f2cb-70ce-45fd-adde-74f4be96cf0f # redactor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bdd105b-2e9f-4ac8-b610-f0aa71ab0390
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 620e76ab-9a6f-468e-968d-58b68fd32c00
        userCondition: null
handle: supportToMakeAGame
hasTitleField: false
name: 'Ondersteuning om zelf een spel te maken'
section: 3cb2bd46-d530-4171-ac8a-071b0492c1ac # Ondersteuning om zelf een spel te maken
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
