columnSuffix: null
contentColumnType: string
fieldGroup: fbc67a4a-697c-4b64-bf27-60d2e76ca405 # Spel
handle: assets
instructions: null
name: Bestanden
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:25a453ed-97ea-4480-921e-0c572facc9d3' # Uploads
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:25a453ed-97ea-4480-921e-0c572facc9d3' # Uploads
  restrictedLocationSubpath: /gameAssets
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\FileTypeConditionRule
              -
                - uid
                - ec781362-b46b-445c-8272-614ea715af55
              -
                - operator
                - in
              -
                - values
                -
                  - image
                  - audio
                  - excel
                  - pdf
                  - powerpoint
                  - video
                  - word
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
