columnSuffix: null
contentColumnType: string
fieldGroup: 6a1c89a2-84a5-4ec6-825a-eee41066ca29 # Homepage
handle: featuredBlogPost
instructions: null
name: 'Uitgelichte blogpost'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 2
  minRelations: 2
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  source: null
  sources:
    - 'section:b9c67985-d40e-4cbd-996d-9b6f511a9f48' # Blogberichten
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
