columnSuffix: exomnvgb
contentColumnType: text
fieldGroup: 8fee1281-9138-49c3-8b8e-5343244c2be3 # Common
handle: intro
instructions: null
name: Intro
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
