columnSuffix: pcqozenq
contentColumnType: integer(10)
fieldGroup: fbc67a4a-697c-4b64-bf27-60d2e76ca405 # Spel
handle: leastAmountOfPlayers
instructions: null
name: 'Minimum aantal spelers'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
