columnSuffix: null
contentColumnType: string
fieldGroup: fbc67a4a-697c-4b64-bf27-60d2e76ca405 # Spel
handle: materialList
instructions: null
name: 'Materiaal lijst'
searchable: false
settings:
  contentTable: '{{%matrixcontent_materiallist}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
