columnSuffix: futzgayy
contentColumnType: text
fieldGroup: fbc67a4a-697c-4b64-bf27-60d2e76ca405 # Spel
handle: purpose
instructions: null
name: 'Doel van het spel'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
