columnSuffix: null
contentColumnType: string
fieldGroup: fbc67a4a-697c-4b64-bf27-60d2e76ca405 # Spel
handle: terrain
instructions: null
name: Terrein
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: 0
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:f8b402c2-1415-4442-ad43-66490a00ab05' # Terrein type
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
